id: db-to-github-export
namespace: production
description: "Export archived site from PostgreSQL to GitHub repository as static files"

pluginDefaults:
  - type: io.kestra.plugin.scripts.runner.docker.Docker
    values:
      networkMode: kestra-net

inputs:
  - id: siteName
    type: STRING
    defaults: site1
  - id: githubToken
    type: STRING
    defaults: ""
    description: "GitHub Personal Access Token (ghp_...)"
  - id: gitRepo
    type: STRING
    defaults: https://github.com/KomarovAI/archived-sites
  - id: gitBranch
    type: STRING
    defaults: main
  - id: targetPath
    type: STRING
    defaults: .
  - id: includeAssets
    type: BOOL
    defaults: true

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: "{{ inputs.gitRepo }}"
        branch: "{{ inputs.gitBranch }}"
        username: git_username
        password: "{{ inputs.githubToken }}"

      - id: export_site
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          networkMode: kestra-net
        beforeCommands:
          - pip install -q psycopg2-binary
        timeout: PT10M
        retry:
          type: exponential
          interval: PT5S
          maxAttempts: 3
          maxInterval: PT30S
        script: |
          import os,psycopg2,re
          from pathlib import Path
          from urllib.parse import urlparse,unquote
          print("\n## EXPORT SITE FROM DB")
          c=psycopg2.connect(host='postgres',database='kestra',user='kestra',password='k3str4_s3cr3t')
          cur=c.cursor()
          site='{{inputs.siteName}}'
          target='{{inputs.targetPath}}'
          inc_assets='{{inputs.includeAssets}}'.lower()=='true'
          site_dir=Path(target)/site if target!='.'else Path(site)
          site_dir.mkdir(parents=True,exist_ok=True)
          cur.execute("SELECT COUNT(*)FROM archived_pages WHERE site_name=%s",(site,))
          pg_cnt=cur.fetchone()[0]
          if pg_cnt==0:print(f"ERROR: No pages found for site '{site}'");cur.close();c.close();exit(1)
          print(f"Site: {site} | Pages: {pg_cnt}")
          cur.execute("SELECT url,html_content FROM archived_pages WHERE site_name=%s",(site,))
          for url,html in cur.fetchall():
              parsed=urlparse(url)
              path=unquote(parsed.path).strip('/')or'index.html'
              if not path.endswith(('.html','.htm')):path+='.html'if not'.'in Path(path).name else''
              fp=site_dir/path
              fp.parent.mkdir(parents=True,exist_ok=True)
              fp.write_text(html,encoding='utf-8')
          print(f"✅ Exported {pg_cnt} pages")
          if inc_assets:
              cur.execute("SELECT COUNT(*)FROM archived_assets WHERE site_name=%s",(site,))
              as_cnt=cur.fetchone()[0]
              if as_cnt>0:
                  print(f"Assets: {as_cnt}")
                  cur.execute("SELECT asset_url,content,local_path FROM archived_assets WHERE site_name=%s",(site,))
                  for url,content,lp in cur.fetchall():
                      if lp:ap=site_dir/lp.lstrip('/')
                      else:
                          parsed=urlparse(url)
                          ap=site_dir/unquote(parsed.path).strip('/')
                      ap.parent.mkdir(parents=True,exist_ok=True)
                      ap.write_bytes(bytes(content))
                  print(f"✅ Exported {as_cnt} assets")
              else:print("⚠️  No assets found")
          else:print("Assets: SKIP")
          cur.close();c.close()
          print(f"\nExported to: {site_dir}")

      - id: push_to_git
        type: io.kestra.plugin.git.Push
        username: git_username
        password: "{{ inputs.githubToken }}"
        branch: "{{ inputs.gitBranch }}"
        commitMessage: "Auto-export site {{ inputs.siteName }} from DB [{{ execution.startDate }}]"

  - id: log_complete
    type: io.kestra.plugin.core.log.Log
    message: |
      ========================================
      EXPORT COMPLETE
      Site: {{ inputs.siteName }}
      Repo: {{ inputs.gitRepo }}
      Branch: {{ inputs.gitBranch }}
      Path: {{ inputs.siteName }}/
      ========================================

errors:
  - id: log_failure
    type: io.kestra.plugin.core.log.Log
    message: |
      ========================================
      EXPORT FAILED
      Site: {{ inputs.siteName }}
      Execution: {{ execution.id }}
      Error: Check logs above
      ========================================